USE [master]
GO
CREATE DATABASE [clean93_MarketModule]
 CONTAINMENT = PARTIAL
 GO
ALTER DATABASE [clean93_MarketModule] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [clean93_MarketModule].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [clean93_MarketModule] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [clean93_MarketModule] SET ANSI_NULLS OFF
GO
ALTER DATABASE [clean93_MarketModule] SET ANSI_PADDING OFF
GO
ALTER DATABASE [clean93_MarketModule] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [clean93_MarketModule] SET ARITHABORT OFF
GO
ALTER DATABASE [clean93_MarketModule] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [clean93_MarketModule] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [clean93_MarketModule] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [clean93_MarketModule] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [clean93_MarketModule] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [clean93_MarketModule] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [clean93_MarketModule] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [clean93_MarketModule] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [clean93_MarketModule] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [clean93_MarketModule] SET  DISABLE_BROKER
GO
ALTER DATABASE [clean93_MarketModule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [clean93_MarketModule] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [clean93_MarketModule] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [clean93_MarketModule] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [clean93_MarketModule] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [clean93_MarketModule] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [clean93_MarketModule] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [clean93_MarketModule] SET RECOVERY FULL
GO
ALTER DATABASE [clean93_MarketModule] SET  MULTI_USER
GO
ALTER DATABASE [clean93_MarketModule] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [clean93_MarketModule] SET DB_CHAINING OFF
GO
ALTER DATABASE [clean93_MarketModule] SET DEFAULT_FULLTEXT_LANGUAGE = 1033
GO
ALTER DATABASE [clean93_MarketModule] SET DEFAULT_LANGUAGE = 1033
GO
ALTER DATABASE [clean93_MarketModule] SET NESTED_TRIGGERS = ON
GO
ALTER DATABASE [clean93_MarketModule] SET TRANSFORM_NOISE_WORDS = OFF
GO
ALTER DATABASE [clean93_MarketModule] SET TWO_DIGIT_YEAR_CUTOFF = 2049
GO
ALTER DATABASE [clean93_MarketModule] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO
ALTER DATABASE [clean93_MarketModule] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [clean93_MarketModule] SET DELAYED_DURABILITY = DISABLED
GO
ALTER DATABASE [clean93_MarketModule] SET QUERY_STORE = OFF
GO
ALTER DATABASE [clean93_MarketModule] SET  READ_WRITE
GO
USE [clean93_MarketModule]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Module](
	[Name] [nvarchar](256) NOT NULL,
	[Category] [nvarchar](256) NOT NULL,
	[Requirements] [nvarchar](256) NOT NULL,
	[Description] [nvarchar](256) NOT NULL,
	[Overview] [nvarchar](256) NULL,
	[Contributor] [nvarchar](256) NOT NULL,
	[ModuleFile] [varbinary](max) NOT NULL,
	[Image1] [varbinary](max) NULL,
	[Image2] [varbinary](max) NULL,
	[Image3] [varbinary](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [clean93_MarketModule]
GO
CREATE USER [marketmoduleuser] WITH PASSWORD=N'kepb3aB/HPkCR4HkFg1gqltIUkgKcfShbzY3w9noWNc=', DEFAULT_SCHEMA=[dbo]
GO